# Generated by Django 4.2.19 on 2025-02-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter a brief biography of the blogger'),
        ),
    ]
